
-- Music Rights Royalty Statement Schema (Complete, No NULLs)
-- Generated by export_to_tables.py

-- Drop existing tables (in reverse dependency order)
DROP TABLE IF EXISTS royalty_line_items CASCADE;
DROP TABLE IF EXISTS statement_summaries CASCADE;
DROP TABLE IF EXISTS extraction_metadata CASCADE;
DROP TABLE IF EXISTS statements CASCADE;

-- Statements (one per PDF - document-level metadata)
CREATE TABLE statements (
    id UUID PRIMARY KEY,
    pdf_name VARCHAR(500) NOT NULL,
    vendor_name VARCHAR(255) NOT NULL DEFAULT 'N/A',
    contract_name VARCHAR(255) NOT NULL DEFAULT 'N/A',
    vendor_number VARCHAR(100) NOT NULL DEFAULT 'N/A',
    contract_number VARCHAR(100) NOT NULL DEFAULT 'N/A',
    period_start VARCHAR(50) NOT NULL DEFAULT 'N/A',
    period_end VARCHAR(50) NOT NULL DEFAULT 'N/A',
    total_pages INTEGER NOT NULL DEFAULT 0,
    processed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Statement summaries (earnings summaries, totals - NO NULLs)
CREATE TABLE statement_summaries (
    id UUID PRIMARY KEY,
    statement_id UUID NOT NULL REFERENCES statements(id),
    page_number INTEGER NOT NULL,
    category VARCHAR(255) NOT NULL,
    subcategory VARCHAR(255) NOT NULL DEFAULT 'N/A',
    amount DECIMAL(15,4) NOT NULL DEFAULT 0
);

-- Royalty line items (transaction-level detail - ALL fields required, NO NULLs)
CREATE TABLE royalty_line_items (
    id UUID PRIMARY KEY,
    statement_id UUID NOT NULL REFERENCES statements(id),
    page_number INTEGER NOT NULL,
    item_name VARCHAR(500) NOT NULL,
    item_code VARCHAR(100) NOT NULL DEFAULT 'N/A',
    channel VARCHAR(255) NOT NULL DEFAULT 'N/A',
    units INTEGER NOT NULL DEFAULT 0,
    unit_rate DECIMAL(15,6) NOT NULL DEFAULT 0,
    gross_amount DECIMAL(15,4) NOT NULL DEFAULT 0,
    royalty_rate DECIMAL(8,6) NOT NULL DEFAULT 0,
    royalty_amount DECIMAL(15,4) NOT NULL DEFAULT 0
);

-- Extraction metadata (for debugging/auditing)
CREATE TABLE extraction_metadata (
    id UUID PRIMARY KEY,
    statement_id UUID NOT NULL REFERENCES statements(id),
    page_number INTEGER NOT NULL,
    region_type VARCHAR(50) NOT NULL DEFAULT 'unknown',
    region_confidence DECIMAL(5,4) NOT NULL DEFAULT 0,
    bbox_x1 DECIMAL(10,2) NOT NULL DEFAULT 0,
    bbox_y1 DECIMAL(10,2) NOT NULL DEFAULT 0,
    bbox_x2 DECIMAL(10,2) NOT NULL DEFAULT 0,
    bbox_y2 DECIMAL(10,2) NOT NULL DEFAULT 0,
    layout_detection_time DECIMAL(10,3) NOT NULL DEFAULT 0,
    ocr_processing_time DECIMAL(10,3) NOT NULL DEFAULT 0,
    content_analysis_time DECIMAL(10,3) NOT NULL DEFAULT 0,
    total_processing_time DECIMAL(10,3) NOT NULL DEFAULT 0,
    text_length INTEGER NOT NULL DEFAULT 0,
    has_hallucination BOOLEAN NOT NULL DEFAULT FALSE,
    image_path TEXT NOT NULL DEFAULT 'N/A'
);

-- Indexes for common queries
CREATE INDEX idx_line_items_statement ON royalty_line_items(statement_id);
CREATE INDEX idx_line_items_name ON royalty_line_items(item_name);
CREATE INDEX idx_line_items_code ON royalty_line_items(item_code);
CREATE INDEX idx_line_items_channel ON royalty_line_items(channel);
CREATE INDEX idx_summaries_statement ON statement_summaries(statement_id);
CREATE INDEX idx_summaries_category ON statement_summaries(category);
CREATE INDEX idx_metadata_statement ON extraction_metadata(statement_id);
